### ISSUE TITLE
Edit UI

### ISSUE THREAD

**Issue by chintan0513** [abn15/PassengerCounterApp#1]
I can add a few customised styles according to your project by changing or adding a few CSS codes

**Comment by chintan0513** [comment]
Please assign me this task

**Comment by abn15** [comment]
sure thing..get started

**Comment by chintan0513** [comment]
Thanks 👍🏻

**Comment by chintan0513** [comment]
Which type of background do you want? gradient colour or image?
Could you please describe it?

**Comment by chintan0513** [comment]
I've made changes, just ping me here if you want changes to it.

**Comment by abn15** [comment]
yes can you update it accordingly to the recent merge..there are minor conflicts..rest it seems fine :)

**Comment by chintan0513** [comment]
okay
