### ISSUE TITLE
I want to add a favicon

### ISSUE THREAD

**Issue by TriinK** [abn15/PassengerCounterApp#17]

**Comment by abn15** [comment]
sure get started

**Comment by TriinK** [comment]
It is finished, PR is waiting to be accepted. Added a cool train.

**Comment by abn15** [comment]
i did merge you pr...but the favicon is not there in the deployed version..can you look into this

**Comment by TriinK** [comment]
I see the reference present but the icon file was not deployed to Github Pages.
The problem could be due to reference path, I changed it and created a new PR.

**Comment by DTriin** [comment]
Seema like it worked now so this issue is resolved :)

**Comment by abn15** [comment]
yeah it is :)
