### ISSUE TITLE
Customize the background Blur effect

### ISSUE THREAD

**Issue by Mano-08** [abn15/PassengerCounterApp#19]
- Details
  -  The passenger count in the background blur box is overflowing on incrementing. 
  - That can be resolved by updating css with viewport relative measurements.

 I would like to work on the issue so would you please assign me to this.

## Reference
![issue](https://user-images.githubusercontent.com/95289188/195667804-219d58d3-7d76-41a9-80f8-fe6c06179f13.png)

**Comment by abn15** [comment]
sure thing..
