### ISSUE TITLE
changing the cards opacity

### ISSUE THREAD

**Issue by kusum-chowdhury** [abn15/PassengerCounterApp#2]
it will look better if all the text are align in the center of the screen. please assign me this issue

**Comment by abn15** [comment]
aight go ahead

**Comment by kusum-chowdhury** [comment]
its already been done

**Comment by abn15** [comment]
oh yes but if you want you can fix the total passenger count..it aint that clear

**Comment by kusum-chowdhury** [comment]
what do you want me to change?

**Comment by kusum-chowdhury** [comment]
![Screenshot from 2022-10-13 20-03-59](https://user-images.githubusercontent.com/108144578/195626212-2e30cc49-f74c-463c-8060-499f11e5b8f6.png)

**Comment by kusum-chowdhury** [comment]
how about this?

**Comment by abn15** [comment]
yes looks good..

**Comment by abn15** [comment]
also just update it with the latest merge to avoid conflicts
