### ISSUE TITLE
make website responsive for mobile

### ISSUE THREAD

**Issue by gauravsharmatheofficial** [abn15/PassengerCounterApp#24]
Hey @abn15 I fond this issue. For mobile it should be in center and a little bit bigger.
i wanna work on it
can you please assign it to me and add hacktoberfest and hacktoberfest2022 label to it
![image](https://user-images.githubusercontent.com/104646258/195994676-83e1b6f2-5968-46ff-9139-47dc52720790.png)

**Comment by abn15** [comment]
Sure..do fix the blurr part for mobile version..assinging..go ahead :)

**Comment by Prashant-kr01** [comment]
hey! @abn15 can you please , assign this issue to me i can fix it and can you please add hacktoberfest and hacktoberfest2022 label to it

**Comment by abn15** [comment]
this has already been fixed :/
you can work on other issues
