### ISSUE TITLE
On large saves made, the container is covering entire space

### ISSUE THREAD

**Issue by Mano-08** [abn15/PassengerCounterApp#28]
- The UI is getting disrupted on huge no. of saves made by the user wherein the Box containing the Save 
- & Increment is occupying almost the entire box pushing away the passenger count details
  - It can be rectified by assigning specific width so that data is constrained within the box itself

I would like to work on changing box-specification and preventing content-overflow. So, would you please assign me to this

| ON HUGE SAVES MADE BY USER | 
|-|
|<img src="https://user-images.githubusercontent.com/95289188/196148130-9111c735-d9e5-4421-8826-d9c5a1a1fbfe.png" />|

**Comment by abn15** [comment]
assigned. get started :)
