### ISSUE TITLE
Add child counter

### ISSUE THREAD

**Issue by pranavsuriya-sr** [abn15/PassengerCounterApp#3]
Adding a child counter which will increase the passenger count but will also keep a track of how many below the age of 18 are entering. 
Please assign this issue to me.

**Comment by abn15** [comment]
but then that will increase the actual count

**Comment by abn15** [comment]
but do re explain if im not getting it right

**Comment by pranavsuriya-sr** [comment]
I will add another button. When a child is entering this new button is pressed. For example there are 10 passengers. When this child button is pressed the passenger count increases from 10 to 11. And i will add a child counter. This counter which was initially 0 will now change to one.
 
  :          Passenger    Child
 Initial          10            0
 After           11            1

As the child is also a passenger this is being a done. This change is just to note the child population entering.

**Comment by pranavsuriya-sr** [comment]
Please assign this issue to me

**Comment by abn15** [comment]
sounds good..yes i will assign get started
